packer {
  required_plugins {
    azure = {
      source  = "github.com/hashicorp/azure"
      version = "~> 1"
    }
  }
}

source "azure-arm" "autogenerated_1" {
  azure_tags = {
    dept = "Engineering"
    task = "Image deployment"
  }
  client_id                         = "00000000-0000-0000-0000-000000000000"
  client_secret                     = "client-secret"
  image_offer                       = "0001-com-ubuntu-server-jammy"
  image_publisher                   = "canonical"
  image_sku                         = "22_04-lts"
  location                          = "West Europe"
  managed_image_name                = "managed-image-name"
  managed_image_resource_group_name = "resource-group-name"
  os_type                           = "Linux"
  subscription_id                   = "00000000-0000-0000-0000-000000000000"
  tenant_id                         = "00000000-0000-0000-0000-000000000000"
  vm_size                           = "Standard_DS2_v2"
}

build {
  sources = [
    "source.azure-arm.autogenerated_1"
  ]

  provisioner "shell" {
    execute_command = "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'"
    inline = [
      "apt-get update",
      "apt-get upgrade -y",
      "cd /home",
      "apt install -y curl git jq libicu70 wget apt-transport-https software-properties-common",
      "wget -q https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb",
      "dpkg -i packages-microsoft-prod.deb",
      "rm packages-microsoft-prod.deb",
      "apt update",
      "apt-get install -y powershell",
      "mkdir -p /etc/apt/keyrings",
      "curl -sLS https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | tee /etc/apt/keyrings/microsoft.gpg > /dev/null",
      "chmod go+r /etc/apt/keyrings/microsoft.gpg",
      "echo 'deb [arch=`dpkg --print-architecture` signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ $(lsb_release -cs) main' | tee /etc/apt/sources.list.d/azure-cli.list",
      "apt-get update",
      "apt-get install azure-cli",
      "/usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0 && sync"
    ]
    inline_shebang = "/bin/sh -x"
  }
}
